pipeline {
    agent {
        any {
            tools { 
                maven 'Maven' 
                jdk 'jdk8' 
            }
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo start clean package'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
